[package]
name = "healer"
version = "0.0.0"
authors = ["Hao Sun <sunhao.th@gmail.com>"]
edition = "2018"
description = "Healer: kernel fuzzer inspired by Syzkaller."
license = "Apache-2.0"

[dependencies]
tokio = {version = "1.0", features = ["rt", "fs", "io-util"]} # for background io.
rustc-hash = "1.1"      # for quick hashmap and hashset, secure cryptographic hash is unnecessary here
rand = "0.8"            # for generation and mutation. 
bv = "0.11.1"           # for mem mark in pointer type generation.
bytes = "1.0"           # for serialization of prog.
iota = "0.2"            # for constant calculation.
shared_memory = "0.11"  # for qemu ivshmem.
json = "0.12"           # for syz description parsing.
thiserror = "1.0"       # for error hanlding.

[dev-dependencies]  
criterion = "0.3"

[[bench]]
name = "gen"
harness = false

[profile.release]
lto = true