[package]
name = "hlc"
version = "0.0.0"
authors = ["Hao Sun <sunhaoyl@outlook.com>"]
edition = "2018"
description = "Compiler of syz-lang"
license = "Apache-2.0"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
