[package]
name = "fuzzer"
version = "0.1.0"
authors = ["sam <sunhaoyl@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = {path="../core"}
executor = {path = "../executor"}
fots={path="../fots"}
serde ={ version= "1.0.104" ,features = ["derive"]}
bincode = "1.2.1"
lazy_static = "1.4.0"
port_check = "0.1.5"
tokio = {version="0.2.11",features=["full"]}
bytes = "0.5.4"
toml = "0.5.6"
structopt = {version="0.3.7",default-features=true}