[package]
name = "core"
version = "0.1.0"
authors = ["sam <sunhaoyl@outlook.com>"]
edition = "2018"
description = "Program generation, mutation, minimiation of healer"
license = "Apache"

[dependencies]
fots={path="../fots"}
ndarray = "0.13.0"
rand = "0.7.3"
bitset-fixed = "0.1.0"
maplit = "1.0.2"