[package]
name = "healer-fuzzer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
healer-core = {path = "../healer-core"}
healer_alloc = {path = "../healer-utils/healer_alloc"}